version: '3.8'

services:
  recipebook.api:
    image: recipebookapi
    build:
      context: .
      dockerfile: Source/Common/RecipeBook.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - database
    networks:
      - recipebook-network
    restart: on-failure  # Only restart on failure, not always

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=bG9jYWxob3N0
      - MYSQL_DATABASE=DB_RecipeBook
    ports:
      - "3306:3306"
    networks:
      - recipebook-network
    restart: always  # Always restart the database container

networks:
  recipebook-network:
    driver: bridge  # Use the bridge network driver
