version: '3.8'

services:
  recipebook.api:
    container_name: api
    image: recipebook.api
    build:
      context: .
      dockerfile: Source/Common/RecipeBook.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - recipebook-network
    restart: always
  
  database:
    container_name: database
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=bG9jYWxob3N0
      - MYSQL_DATABASE=DB_Test
    ports:
      - "3306:3306"
    networks:
      - recipebook-network
    restart: always

networks:
  recipebook-network:
    driver: bridge