//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Resources;

namespace RecipeBook.Exceptions;

using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ErrorMessages
{

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ErrorMessages()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeBook.Exceptions.ErrorMessages", typeof(ErrorMessages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    public static string CATEGORIA_RECEITA_INVALIDA => ResourceManager.GetString("CATEGORIA_RECEITA_INVALIDA", resourceCulture);

    public static string CODIGO_NAO_ENCONTRADO => ResourceManager.GetString("CODIGO_NAO_ENCONTRADO", resourceCulture);

    public static string EMAIL_JA_REGISTRADO => ResourceManager.GetString("EMAIL_JA_REGISTRADO", resourceCulture);

    public static string EMAIL_USUARIO_EMBRANCO => ResourceManager.GetString("EMAIL_USUARIO_EMBRANCO", resourceCulture);

    public static string EMAIL_USUARIO_INVALIDO => ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);

    public static string ERRO_DESCONHECIDO => ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);

    public static string ESTA_CONEXAO_JA_EXISTE => ResourceManager.GetString("ESTA_CONEXAO_JA_EXISTE", resourceCulture);

    public static string LOGIN_INVALIDO => ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);

    public static string MODOPREPARO_RECEITA_EMBRANCO => ResourceManager.GetString("MODOPREPARO_RECEITA_EMBRANCO", resourceCulture);

    public static string NOME_USUARIO_EMBRANCO => ResourceManager.GetString("NOME_USUARIO_EMBRANCO", resourceCulture);

    public static string RECEITA_INGREDIENTE_PRODUTO_EMBRANCO => ResourceManager.GetString("RECEITA_INGREDIENTE_PRODUTO_EMBRANCO", resourceCulture);

    public static string RECEITA_INGREDIENTE_QUANTIDADE_EMBRANCO => ResourceManager.GetString("RECEITA_INGREDIENTE_QUANTIDADE_EMBRANCO", resourceCulture);

    public static string RECEITA_INGREDIENTES_REPETIDOS => ResourceManager.GetString("RECEITA_INGREDIENTES_REPETIDOS", resourceCulture);

    public static string RECEITA_MINIMO_UM_INGREDIENTE => ResourceManager.GetString("RECEITA_MINIMO_UM_INGREDIENTE", resourceCulture);

    public static string RECEITA_NAO_ENCONTRADA => ResourceManager.GetString("RECEITA_NAO_ENCONTRADA", resourceCulture);

    public static string SENHA_ATUAL_INVALIDA => ResourceManager.GetString("SENHA_ATUAL_INVALIDA", resourceCulture);

    public static string SENHA_USUARIO_EMBRANCO => ResourceManager.GetString("SENHA_USUARIO_EMBRANCO", resourceCulture);

    public static string SENHA_USUARIO_MINIMO_OITO_CARACTERES => ResourceManager.GetString("SENHA_USUARIO_MINIMO_OITO_CARACTERES", resourceCulture);

    public static string SENHA_USUARIO_INVALIDA => ResourceManager.GetString("SENHA_USUARIO_INVALIDA", resourceCulture);

    public static string TELEFONE_USUARIO_EMBRANCO => ResourceManager.GetString("TELEFONE_USUARIO_EMBRANCO", resourceCulture);

    public static string TELEFONE_USUARIO_INVALIDO => ResourceManager.GetString("TELEFONE_USUARIO_INVALIDO", resourceCulture);

    public static string TEMPO_PREPARO_INVALIDO => ResourceManager.GetString("TEMPO_PREPARO_INVALIDO", resourceCulture);

    public static string TITULO_RECEITA_EMBRANCO => ResourceManager.GetString("TITULO_RECEITA_EMBRANCO", resourceCulture);

    public static string TOKEN_EXPIRADO => ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);

    public static string USUARIO_NAO_ENCONTRADO => ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);

    public static string USUARIO_SEM_PERMISSAO => ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);

    public static string VOCE_NAO_PODE_EXECUTAR_ESTA_OPERACAO => ResourceManager.GetString("VOCE_NAO_PODE_EXECUTAR_ESTA_OPERACAO", resourceCulture);

    public static string TELEFONE_JA_REGISTRADO => ResourceManager.GetString("TELEFONE_JA_REGISTRADO", resourceCulture);

    public static string NOME_USUARIO_INVALIDO => ResourceManager.GetString("NOME_USUARIO_INVALIDO", resourceCulture);

    public static string SENHA_USUARIO_MAXIMO_DEZESSEIS_CARACTERES => ResourceManager.GetString("SENHA_USUARIO_MAXIMO_DEZESSEIS_CARACTERES", resourceCulture);

    public static string TOKEN_INVALIDO => ResourceManager.GetString("TOKEN_INVALIDO", resourceCulture);

    public static string EMAIL_NAO_CONFIRMADO => ResourceManager.GetString("EMAIL_NAO_CONFIRMADO", resourceCulture);

    public static string CODIGO_INVALIDO => ResourceManager.GetString("CODIGO_INVALIDO", resourceCulture);
}