//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeBook.Exceptions;

using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ErrorMessages
{

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ErrorMessages()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeBook.Exceptions.ErrorMessages", typeof(ErrorMessages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to A categoria da receita é inválida..
    /// </summary>
    public static string CATEGORIA_RECEITA_INVALIDA
    {
        get
        {
            return ResourceManager.GetString("CATEGORIA_RECEITA_INVALIDA", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Código não encontrado..
    /// </summary>
    public static string CODIGO_NAO_ENCONTRADO
    {
        get
        {
            return ResourceManager.GetString("CODIGO_NAO_ENCONTRADO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O e-mail informado já esta registrado na base de dados..
    /// </summary>
    public static string EMAIL_JA_REGISTRADO
    {
        get
        {
            return ResourceManager.GetString("EMAIL_JA_REGISTRADO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O e-mail do usuário deve ser informado..
    /// </summary>
    public static string EMAIL_USUARIO_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("EMAIL_USUARIO_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O e-mail do usuário é inválido..
    /// </summary>
    public static string EMAIL_USUARIO_INVALIDO
    {
        get
        {
            return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Erro desconhecido..
    /// </summary>
    public static string ERRO_DESCONHECIDO
    {
        get
        {
            return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Esta conexão já existe..
    /// </summary>
    public static string ESTA_CONEXAO_JA_EXISTE
    {
        get
        {
            return ResourceManager.GetString("ESTA_CONEXAO_JA_EXISTE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O e-mail e/ou senha estão incorretos..
    /// </summary>
    public static string LOGIN_INVALIDO
    {
        get
        {
            return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O modo de preparo da receita deve ser informado..
    /// </summary>
    public static string MODOPREPARO_RECEITA_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("MODOPREPARO_RECEITA_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O nome do usuário deve ser informado..
    /// </summary>
    public static string NOME_USUARIO_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("NOME_USUARIO_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O produto do ingrediente deve ser informado..
    /// </summary>
    public static string RECEITA_INGREDIENTE_PRODUTO_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("RECEITA_INGREDIENTE_PRODUTO_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to A quantidade do ingrediente deve ser informada..
    /// </summary>
    public static string RECEITA_INGREDIENTE_QUANTIDADE_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("RECEITA_INGREDIENTE_QUANTIDADE_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Exitem ingredientes repetidos na sua lista..
    /// </summary>
    public static string RECEITA_INGREDIENTES_REPETIDOS
    {
        get
        {
            return ResourceManager.GetString("RECEITA_INGREDIENTES_REPETIDOS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to A receita deve ter no mínimo um ingrediente..
    /// </summary>
    public static string RECEITA_MINIMO_UM_INGREDIENTE
    {
        get
        {
            return ResourceManager.GetString("RECEITA_MINIMO_UM_INGREDIENTE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Receita não encontrada..
    /// </summary>
    public static string RECEITA_NAO_ENCONTRADA
    {
        get
        {
            return ResourceManager.GetString("RECEITA_NAO_ENCONTRADA", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Senha atual é inválida..
    /// </summary>
    public static string SENHA_ATUAL_INVALIDA
    {
        get
        {
            return ResourceManager.GetString("SENHA_ATUAL_INVALIDA", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to A senha do usuário deve ser informada..
    /// </summary>
    public static string SENHA_USUARIO_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("SENHA_USUARIO_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to A senha deve conter no minimo 8 caracteres..
    /// </summary>
    public static string SENHA_USUARIO_MINIMO_OITO_CARACTERES
    {
        get
        {
            return ResourceManager.GetString("SENHA_USUARIO_MINIMO_OITO_CARACTERES", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to O senha do usuário é inválido...
    /// </summary>
    public static string SENHA_USUARIO_INVALIDO
    {
        get
        {
            return ResourceManager.GetString("SENHA_USUARIO_INVALIDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O telefone do usuário deve ser informado..
    /// </summary>
    public static string TELEFONE_USUARIO_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("TELEFONE_USUARIO_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O telefone do usuário deve estar no formato XX X XXXX-XXXX.
    /// </summary>
    public static string TELEFONE_USUARIO_INVALIDO
    {
        get
        {
            return ResourceManager.GetString("TELEFONE_USUARIO_INVALIDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O tempo de preparo é invalido..
    /// </summary>
    public static string TEMPO_PREPARO_INVALIDO
    {
        get
        {
            return ResourceManager.GetString("TEMPO_PREPARO_INVALIDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O título da receita deve ser informado..
    /// </summary>
    public static string TITULO_RECEITA_EMBRANCO
    {
        get
        {
            return ResourceManager.GetString("TITULO_RECEITA_EMBRANCO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Faça login novamente no App..
    /// </summary>
    public static string TOKEN_EXPIRADO
    {
        get
        {
            return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usuário não encontrado.
    /// </summary>
    public static string USUARIO_NAO_ENCONTRADO
    {
        get
        {
            return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Você não tem permissão para acessar este recurso..
    /// </summary>
    public static string USUARIO_SEM_PERMISSAO
    {
        get
        {
            return ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Você não pode executar esta operação..
    /// </summary>
    public static string VOCE_NAO_PODE_EXECUTAR_ESTA_OPERACAO
    {
        get
        {
            return ResourceManager.GetString("VOCE_NAO_PODE_EXECUTAR_ESTA_OPERACAO", resourceCulture);
        }
    }

    /// <summary>
    ///    Looks up a localized string similar to O telefone do usuário ja foi registrado
    ///</summary>
    public static string TELEFONE_JA_REGISTRADO
    {
        get
        {
            return ResourceManager.GetString("TELEFONE_JA_REGISTRADO", resourceCulture);
        }
    }
}